import { Card } from '../components/Card';
import { TrainingIcon, BoltIcon } from '../icons';

export function Training() {
  return (
    <div className="px-5 pt-6 pb-24 animate-fade-in">
      <div className="mb-6">
        <h1 className="text-xl font-bold">Training</h1>
        <p className="text-text-muted text-sm mt-1">Your workout programs</p>
      </div>

      <Card className="mb-4 flex flex-col items-center py-8">
        <div className="w-14 h-14 rounded-2xl bg-blue-400/10 flex items-center justify-center mb-4">
          <BoltIcon size={28} color="#60A5FA" />
        </div>
        <div className="text-sm font-semibold mb-1">AI Training Plan</div>
        <div className="text-text-muted text-xs text-center max-w-[220px]">
          Get a personalized workout program generated by AI based on your goals and experience
        </div>
      </Card>

      <Card className="flex items-center justify-center py-12">
        <div className="text-center">
          <TrainingIcon size={32} color="#616161" className="mx-auto mb-3" />
          <div className="text-text-muted text-sm">No workouts yet</div>
          <div className="text-text-muted text-xs mt-1">Generate your first program above</div>
        </div>
      </Card>
    </div>
  );
}
